# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="Which services in datadog are missing from service catalog?"
REPO_LICENSE=""
REPO_TOPICS="datadog,datadog-service-catalog,service-management,services"

# URLs section
REPO_GIT_SSH="git@github.com:fini-net/datadog-service-analyzer.git"
REPO_WEB_URL="https://github.com/fini-net/datadog-service-analyzer"

# Derived values
REPO_ORG_NAME="fini-net"
REPO_REPO_NAME="datadog-service-analyzer"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="false"
FLAG_CLAUDE_REVIEW="false"
FLAG_COPILOT_REVIEW="false"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "datadog"
    "datadog-service-catalog"
    "service-management"
    "services"
)
